#!/usr/bin/env bash

set -e

if [[ `uname` == "Darwin" ]];
then
    echo "Installing .dotfiles for macOS..."
    CONFIG="install_macos.conf.yaml"
elif [[ `uname` == "Linux" ]];
then
    echo "Installing .dotfiles for ArchLinux..."
    CONFIG="install_arch.conf.yaml"
else
    echo "OS not supported."
    exit 1
fi
DOTBOT_DIR="third_party/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
