#!/bin/zsh
# Set up macOS-specific variables
if [[ `uname` == "Darwin" ]];
then
    # Apple Silicon specific settings
    if [[ `uname -m` == "arm64" ]];
    then
        # Add Homebrew to PATH on Apple Silicon
        export PATH="/opt/homebrew/bin:$PATH"
        export PATH="/opt/homebrew/sbin:$PATH"

        # Set paths to find libraries
        export CPATH=/opt/homebrew/include
        export LIBRARY_PATH=/opt/homebrew/lib
    else
        # Set up PATH to find Homebrew installed binaries.
        export PATH="$PATH:/usr/local/sbin"
    fi

    # Set up PostgreSQL binaries
    export PATH="$PATH:$(brew --prefix postgresql@16)/bin"

    # Set up python to point to Homebrew's version
    export PATH="$(brew --prefix python@3.12)/libexec/bin:$PATH"

    # Set up eza completions
    export FPATH="$(brew --prefix eza)/completions/zsh:$FPATH"

    # Set up JAVA_HOME to use JDK
    export JAVA_HOME="$(/usr/libexec/java_home -v 21)"

    # Suppress the following warning:
    # `malloc: nano zone abandoned due to inability to reserve vm space.`
    export MallocNanoZone=0

    # Disable AddressSanitizerContainerOverflow to suppress warning for potential false positives
    export ASAN_OPTIONS=detect_container_overflow=0

    # Set PostgreSQL directory for easier start and stop of the server.
    export PGDATA="/usr/local/var/postgresql@16"

    # Add llvm clang to PATH
    export PATH="$(brew --prefix llvm@17)/bin:$PATH"
fi

# Set up locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Set up dofiles path
export DOTFILES=${HOME}/.dotfiles

# Set up default utilities.
export EDITOR=nvim
export VISUAL=nvim
export PAGER=less
export DIFFPROG='nvim -d'

# Set up default C and C++ compilers.
# https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html
if [[ `uname` == "Darwin" ]];
then
    export CC="$(brew --prefix llvm@17)/bin/clang"
    export CXX="$(brew --prefix llvm@17)/bin/clang++"
elif [[ `uname` == "Linux" ]];
then
    export CC=/usr/bin/clang
    export CXX=/usr/bin/clang++
fi

# Set up ninja output format.
# https://ninja-build.org/manual.html#_environment_variables
export NINJA_STATUS="[%p|%s/%t|%es]"
