# Set up PATH to find Homebrew installed binaries.
# https://docs.brew.sh/Formula-Cookbook#variables-for-directory-locations
if [[ "$OSTYPE" == "darwin"* ]];
then
    export PATH="$PATH:/usr/local/sbin"
fi

# Set up JAVA_HOME to use JDK
if [[ "$OSTYPE" == "darwin"* ]];
then
    export JAVA_HOME="/usr/libexec/java_home -v 1.8" # openjdk-8
#    export JAVA_HOME="/usr/libexec/java_home -v 12" # openjdk-12
fi

# Set up Google depot_tools
if [[ "$OSTYPE" == "darwin"* ]];
then
    export PATH="$PATH:/opt/depot_tools"
fi

# Set up postgresql binaries
if [[ "$OSTYPE" == "darwin"* ]];
then
    export PATH="$PATH:/usr/local/opt/postgresql@16/bin"
fi

# Set `python` to Homebrew version
if [[ "$OSTYPE" == "darwin"* ]];
then
    export PATH="$(brew --prefix)/opt/python/libexec/bin:$PATH"
fi

# Set up eza completions
if [[ "$OSTYPE" == "darwin"* ]];
then
    export FPATH="/usr/local/opt/eza/completions/zsh:$FPATH"
fi

# Set up locale
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Set up dofiles path
export DOTFILES=${HOME}/.dotfiles
